### ISSUE TITLE
get session gets idle (by timeout) when using tornado_sqlalchemy make_session_factory

### ISSUE THREAD

**Issue by itamarf84** [siddhantgoel/tornado-sqlalchemy#43] opened 2018-11-11 11:58 UTC
When creating a connection pool using tornado_sqlalchemy.make_session_factory there is a default timeout of 30 min.
this timeout waits for thread notification on the pool, which in case async code is used will block execution for that time (and in extreme scenarios will create a deadlock), and will break the async model.

probably need to create some async session factory.

in order to reproduce define pool_size as 1 an run several concurent request

**Comment by siddhantgoel** [comment] 2018-11-11 19:11
Thanks for the report. I just wrote a test case based on your description that reproduces this behavior. I'll try to find some time in the next few days to fix this. Meanwhile, if you'd like to submit a PR - you're most welcome. :)

**Comment by siddhantgoel** [comment] 2018-11-13 18:04
Looks like [`scoped_session`](https://docs.sqlalchemy.org/en/latest/orm/contextual.html#sqlalchemy.orm.scoping.scoped_session) could work well for an async session factory.

**Comment by itamarf84** [comment] 2018-11-14 09:06
scoped_session uses session_factory which is the component that originated the issue.
i can think of 2 possible solutions:
1. create new engine for async that uses async-queue - https://docs.python.org/3/library/asyncio-queue.html

2. create new pool_class that work async (and will either sleep in async manner or wait on connection pool)

**Comment by siddhantgoel** [comment] 2018-11-14 09:47
1. Async queues are not thread safe, and `as_future` relies on running the query in a `ThreadPoolExecutor`. Not sure if an async queue would work here.
2. I'd really not like to mess with connection pooling and let SQLAlchemy handle all that stuff. We're working in terms of sessions anyway.

At the moment what ends up happening is that the `as_future` uses the session from the main thread and sends it to a `ThreadPoolExecutor` which runs the query in a separate thread. In the meantime if the session is used on the main thread, this is bad because sessions are not thread safe but are supposed to be thread-local.

Using a `scoped_session` would at least make sure that the sessions are not being shared across threads.

Another alternative would be to use [`StackContext`](https://www.tornadoweb.org/en/stable/stack_context.html) as the scoping function for `scoped_session`, but that's already deprecated in 5.0 so I'm not sure if I should use it anymore.

**Comment by siddhantgoel** [comment] 2018-11-14 09:50
Btw this is the test case I'm using locally to fix this behavior.

```python
@gen_test
async def test_concurrent_requests_using_async(self):
    Base = declarative_base()

    factory = make_session_factory(postgres_url, pool_size=1)

    Base.metadata.create_all(factory.engine)

    sessions = [factory.make_session() for _ in range(15)]

    results = [
        await as_future(session.query(User).count) for session in sessions
    ]

    for result in results:
        self.assertEqual(result, 0)

    for session in sessions:
        session.close()

    Base.metadata.drop_all(factory.engine)
```

Is this what you meant or something else?

**Comment by itamarf84** [comment] 2018-11-14 10:00
this example probably won't get the real issue:
1. query should be long running like: as_future(session.execute('sleep(20)'))
2. in order to run concurrently create one session at a time and run the function in a multi-process mode
3. make_session_factory(postgres_url, pool_size=1) shuold be a static code (outside the function)

**Comment by siddhantgoel** [comment] 2018-11-14 15:02
1. OK, makes sense.
2. But that's what `await as_future(...)` is doing, right? Each query gets submitted to the thread pool so that they all end up running concurrently in separate threads.
3. Why should it be outside the function?

**Comment by lidadreamer** [comment] 2019-01-21 08:05
is this problem fixed？

**Comment by siddhantgoel** [comment] 2019-01-21 17:36
A combination of waiting further clarification from @itamarf84 and me not having a lot of spare time these days. You're welcome to contribute if you like.

**Comment by siddhantgoel** [comment] 2020-11-21 20:41
Marking as closed because of lack of more information. Feel free to reopen.

**Closed as completed by siddhantgoel** 2020-11-21 20:41 UTC
Labels: needs clarification
